apiVersion: v1
kind: Secret
metadata:
  name: loan-engine-secrets
  namespace: loan-engine
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "postgres"
  JWT_SECRET: "LoanDecisionEngine2021SecretKeyForJWTTokenSigning"
